# Sets the URL name of the quickstart on public I/O (required)
slug: hackathon-2022-group-8

# Displayed in the UI (required)
title: Hackathon 2022 Group 8

# Long-form description of the quickstart (required)
description: |
  Nutz & Boltz is a dashboard to provide developers a view into the efficiency of their service while also providing a glimpse into possible security issues. This dashboard gives you: 
    Pageload Time: Pageloads by time taken
    User Operating System: Number of users for a particular OS
    Mobile Device Crashes: Lists session ID and city of mobile crashes
    Cloud Provider: Lists session ID and Cloud Provider & Instance (if there are any)

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  This quickstart provides a dashboard for quickly viewing efficiency through pageload times, user operating system types, mobile device crashes and cloud provider list.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Evan Kim
  - Evan Burchett
  - Renee Petit

# Keywords for filtering / searching criteria in the UI
keywords:
  - optimization
  - pageload
  - security

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - example-install
dashboards:
  - Hackathon 2022 Group 8
# Documentation references
documentation:
  - name: Installation docs
    url: docs.newrelic.com
    description: Description about this doc reference

# Content / Design
icon: logo.png
website: https://github.com/reneelpetit/newrelic-quickstarts
